### ISSUE TITLE
Build Bug

### ISSUE THREAD

**Issue by MunsMan** [MunsMan/ImageGrid#2]
There is probably a dependency missing:

## Log

python3 setup.py install
running install
running bdist_egg
running egg_info
creating ImageGrid.egg-info
writing ImageGrid.egg-info/PKG-INFO
writing dependency_links to ImageGrid.egg-info/dependency_links.txt
writing entry points to ImageGrid.egg-info/entry_points.txt
writing requirements to ImageGrid.egg-info/requires.txt
writing top-level names to ImageGrid.egg-info/top_level.txt
writing manifest file 'ImageGrid.egg-info/SOURCES.txt'
reading manifest file 'ImageGrid.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'ImageGrid.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/grid
copying grid/grid.py -> build/lib/grid
copying grid/__init__.py -> build/lib/grid
copying grid/main.py -> build/lib/grid
creating build/bdist.macosx-11-x86_64
creating build/bdist.macosx-11-x86_64/egg
creating build/bdist.macosx-11-x86_64/egg/grid
copying build/lib/grid/grid.py -> build/bdist.macosx-11-x86_64/egg/grid
copying build/lib/grid/__init__.py -> build/bdist.macosx-11-x86_64/egg/grid
copying build/lib/grid/main.py -> build/bdist.macosx-11-x86_64/egg/grid
byte-compiling build/bdist.macosx-11-x86_64/egg/grid/grid.py to grid.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/grid/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/grid/main.py to main.cpython-39.pyc
creating build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/PKG-INFO -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/SOURCES.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/dependency_links.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/entry_points.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/requires.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying ImageGrid.egg-info/top_level.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/ImageGrid-0.9.0-py3.9.egg' and adding 'build/bdist.macosx-11-x86_64/egg' to it
removing 'build/bdist.macosx-11-x86_64/egg' (and everything under it)
Processing ImageGrid-0.9.0-py3.9.egg
Copying ImageGrid-0.9.0-py3.9.egg to /usr/local/lib/python3.9/site-packages
Adding ImageGrid 0.9.0 to easy-install.pth file
Installing grid script to /usr/local/bin

Installed /usr/local/lib/python3.9/site-packages/ImageGrid-0.9.0-py3.9.egg
Not found: numpy
Not found: Pillow
Not found: pathlib
Not found: click
Processing dependencies for ImageGrid==0.9.0
Searching for numpy
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/0b/a7/e724c8df240687b5fd62d8c71f1a6709d455c4c09432c7412e3e64f4cbe5/numpy-1.21.1.zip#sha256=dff4af63638afcc57a3dfb9e4b26d434a7a602d225b42d746ea7fe2edf1342fd
Best match: numpy 1.21.1
Processing numpy-1.21.1.zip
Writing /var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.cfg
Running numpy-1.21.1/setup.py -q bdist_egg --dist-dir /var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/egg-dist-tmp-necd_gxp
Running from numpy source directory.
Cythonizing sources
Processing numpy/random/_bounded_integers.pxd.in
Processing numpy/random/_philox.pyx
Traceback (most recent call last):
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 59, in process_pyx
    import Cython
ModuleNotFoundError: No module named 'Cython'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 239, in <module>
    main()
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 235, in main
    find_process_files(root_dir)
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 226, in find_process_files
    process(root_dir, fromfile, tofile, function, hash_db)
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 192, in process
    processor_function(fromfile, tofile)
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/tools/cythonize.py", line 66, in process_pyx
    raise OSError(msg) from e
OSError: Cython needs to be installed in Python as a module
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 447, in <module>
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 429, in setup_package
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 235, in generate_cython
RuntimeError: Running cythonize failed!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucagoslar/Documents/ImageGrid/setup.py", line 21, in <module>
    setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 744, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1162, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.9/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 447, in <module>
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 429, in setup_package
  File "/var/folders/jt/5kqwk7_x6gl_c9tn7gqllrv40000gn/T/easy_install-aw6jyw11/numpy-1.21.1/setup.py", line 235, in generate_cython
RuntimeError: Running cythonize failed!

## Possible Solution

There is probably a Cython import missing. Adding this dependency, may solve the problem. Build Testing needed

**Comment by MunsMan** [comment]
Testing should be handelt by #1
